# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13923e9da45bd04598e406bd146231c2c1590e7c05b07df0ba9f88c970068778d798ab4d257fe336063f7f1f404ac909fda97c7970198e8edd2586a27a0457c2

test:
  secret_key_base: 4ac9a1405a7b4c32703a03b10dae452e7a5afd72892d4652f6a591dad28805f2782a231d81d490eb6aaff48918018fcf9218f03aa12c72d5a8aa2b65b1b4c190

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
